### PR TITLE
updated seqneut pipeline and neutcurve with latest version

### PR DESCRIPTION
**Pull request by anloes**
This update uses the latest version of seqneut-pipeline and neutcurve, and includes the updated files from running the pipeline with this change.

### CODE REVIEW

**Comment by jbloom** [comment]
@anloes, I think the results here are not up-to-date? For instance, I think that with the updated pipeline the aggregated titers should be group specific and there should not be any aggregated titers file just called `titers.csv`?

I think this could be some combination of not removing the old output and then not updating the `.gitignore` for the new pipeline?

If it seems like this is the case, I would suggest fully removing the results, then re-running the pipeline and making sure you have update the `.gitignore` as needed.

**Comment by anloes** [comment]
Yes, you are right, I forgot to remove the old titers file. I am rerunning now with everything removed. Unfortunately, given that our fitting parameters have changed, even though the overall results have not changed, I will need to remake all the figures prior to resubmission with the updated output.

**Comment by jbloom** [comment]
Yes, before merging the pull request for this I think it would be good to make plots that show:
1. The correlation between the final titers w the old pipeline and this one for all sera.
2. Any sera that had titers in old pipeline but not this one, and vice versa (due to different QC)/

We can look at above plots to make sure results virtually identical.

Yes, you may want to remake figures if any data for them has changed perceptibly.

**Comment by anloes** [comment]
image
Update completed. 
The results are well correlated between previous pipeline and updated. There was one virus that we did not calculate a titer for previously for which we now have a titer. All virus:serum pairs have titers.

**Comment by jbloom** [comment]
Mostly looks good, @anloes, but the README now links to non-existent file for the aggregated titers. Can you update the README accordingly too?

**Comment by anloes** [comment]
Okay, README now updated.

**Pull request merged**
